name: 'Zigbee Thermostat Jamer007'
defaultProfile: 'base-thermostat'
packageKey: 'zigbee-thermostat-jamer007'
description: 'Stock Driver Modified for Sinope thermostats.'
permissions:
  zigbee: {}
  lan: {}
